name: GitHub Auth Generator
description: Generate various kinds of GitHub authentication tokens, from other kinds of authentication tokens
inputs:
  tokenType:
    description: type of token to generate
    required: true
  debug:
    description: toggle debug log output
    required: false
    default: false
  authorization:
    description: toggle authorization mode
    required: false
    default: false
  appId:
    description: GitHub app ID
    required: false
    default: null
  privateKey:
    description: PEM-encoded private key content for the app
    required: false
    default: null
  installationId:
    description: installation ID for the app
    required: false
    default: null
  orgName:
    description: organization name to act on
    required: false
    default: null
  repoName:
    description: repo name to act on
    required: false
    default: null
  personalAccessToken:
    description: personal access token to use for generation
    required: false
    default: null
outputs:
  token:
    description: generated token
runs:
  using: node12
  main: src/action.js
